// sync-designated-person/index.ts
// Upserts a designated_persons row using the service role key (no user auth needed)
// and returns the acceptance_token so the caller can embed it in the invitation email.
//
// Deploy: supabase functions deploy sync-designated-person --project-ref kypzbbupzuaukdkjeghu --no-verify-jwt

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const SUPABASE_URL      = 'https://kypzbbupzuaukdkjeghu.supabase.co'
const SERVICE_ROLE_KEY  = Deno.env.get('SERVICE_ROLE_KEY')!

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS })

  const {
    owner_id,
    first_name,
    last_name,
    email,
    phone_number,
    relationship,
    can_access_photos,
    can_view_arrangements,
  } = await req.json()

  if (!owner_id || !email) {
    return new Response(JSON.stringify({ error: 'owner_id and email are required' }), {
      status: 400, headers: { ...CORS, 'Content-Type': 'application/json' },
    })
  }

  // Upsert the row. On conflict (owner_id, email) update the fields.
  // The acceptance_token is generated by the DB DEFAULT on first insert and
  // left unchanged on subsequent upserts so existing links stay valid.
  const upsertRes = await fetch(
    `${SUPABASE_URL}/rest/v1/designated_persons?on_conflict=owner_id,email`,
    {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${SERVICE_ROLE_KEY}`,
        'apikey': SERVICE_ROLE_KEY,
        'Content-Type': 'application/json',
        'Prefer': 'resolution=merge-duplicates,return=representation',
      },
      body: JSON.stringify({
        owner_id,
        first_name,
        last_name,
        email,
        phone_number:          phone_number ?? '',
        relationship:          relationship ?? '',
        invitation_accepted:   false,
        can_access_photos:     can_access_photos ?? false,
        can_view_arrangements: can_view_arrangements ?? true,
      }),
    }
  )

  if (!upsertRes.ok) {
    const err = await upsertRes.text()
    console.error('Upsert error:', err)
    return new Response(JSON.stringify({ error: 'DB upsert failed', detail: err }), {
      status: 500, headers: { ...CORS, 'Content-Type': 'application/json' },
    })
  }

  const rows = await upsertRes.json() as { acceptance_token: string }[]
  const acceptance_token = rows[0]?.acceptance_token

  return new Response(JSON.stringify({ ok: true, acceptance_token }), {
    headers: { ...CORS, 'Content-Type': 'application/json' },
  })
})
